version: "5.8"
servers:
  - id: default
    listeners:
      - port: 25
        address: 127.0.0.1
environment:
  uuid:
    version: 4
  controlsocket:
    group: staff
    chmod: "0660"
  privdrop:
    user: halon
    group: halon
  umask: "0027"
  rlimit:
    nofile: 70000
plugins:
  - id: msal
    config:
      tenants:
        - id: tenant1
          cache_file: /tmp/msal_cache.json
          client_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
          authority: https://login.microsoftonline.com/organizations
          scopes:
            - https://outlook.office.com/SMTP.Send